language: node_js
script:
  - ./scripts/install.sh
  - npm run test
cache:
  directories:
    - ~/.npm
notifications:
  email: false
sudo: required
dist: trusty
node_js:
  - '10'
  - '9'
  - '8'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
